### ISSUE TITLE
How to prefix with a variable?

### ISSUE THREAD

**Issue by stefandevo** [jamesmontemagno/steps-set-android-manifest-versions#13]
It seems something is wrong with this step.
I use a variable:

BASE_VERSION: 1.0

then use
- set-android-manifest-versions:
      inputs:
      - manifest_file: "$ANDROID_MANIFEST_PATH"
      - version_code_offset: '10000'
      - version_name: $BASE_VERSION.$BITRISE_BUILD_NUMBER

What happens then is that it creates 1.5 (where 5 is the build number) while I would expect 1.0.5

If I change

BASE_VERSION: 1.0.0

Then I get 1.0.0.5 ...

The same happens for the ios step.

Any idea how to get it right?

**Comment by jamesmontemagno** [comment]
What does the build output say?

I look at the version_name and echo it out:

```
if ! [ -z "${version_name}" ] ; then
  echo " (i) Version Name: ${version_name}"
fi
```

**Comment by stefandevo** [comment]
Hi James. I did some extra testing locally, and I found out what the issue was. I was setting BASE_VERSION: 1.0 -> if I change it to BASE_VERSION: "1.0" than it worked.

**Comment by jamesmontemagno** [comment]
Good to know, i bet it is looking for a string and it thought it was a float or something. Interesting.
