### ISSUE TITLE
 Could not find current Version Code!

### ISSUE THREAD

**Issue by mshearer123** [jamesmontemagno/steps-set-android-manifest-versions#19]
Hey, 
Struggling a bit to get builds with updates version codes.

currently i am seeing this

(i) Provided Android Manifest path: Flatify/app/src/main/AndroidManifest.xml
 (i) Verson Code: 135
 (i) Version Name: 1.0.35
 [!] Could not find current Version Code!

do i need to add placeholder version name and codes to the manifest for them to be written over?

**Comment by jamesmontemagno** [comment]
Yes, you need to have them in the AndroidManifest. I find and parse them out.

**Comment by mshearer123** [comment]
ok, sorry a couple more questions.
1. should the android gradle file also have entries for versionCode and versionName
2. where in the workflow should the step be,  before the gradle runner?

thanks again, i've been trying to get this to work for some time but the upload to google play step always gives me "Failed to upload apk, error: googleapi: Error 403: APK specifies a version code that has already been used"

**Comment by jamesmontemagno** [comment]
You may want to change the offset as it uses the bitrise build number. Not sure what you already submitted. the version code always must be higher.

I don't use gradle at all, there are other steps for that. Perhaps one of those may be better suited.

**Comment by mshearer123** [comment]
ok cool, thanks again

**Comment by SteveGrosbois** [comment]
Try this one if you use gradle : https://github.com/bitrise-community/steps-change-android-versioncode-and-versionname
