### ISSUE TITLE
Add "Build Number Offset" Like "Set Xcode Project Build Number" Step

### ISSUE THREAD

**Issue by gregorymartin** [jamesmontemagno/steps-set-android-manifest-versions#6]
It would be handy if this step added the ability to set an offset that is added to the build number similar to what the "Set Xcode Project Build Number" step does.

https://github.com/bitrise-io/steps-set-xcode-build-number

**Comment by kevinmcmahon** [comment]
This has already been added in 1.0.4 but needs to get propagated to Bitrise (latest is still 1.0.2 there).

**Comment by gregorymartin** [comment]
That's great, do you know when that will happen?

**Comment by jamesmontemagno** [comment]
I think i sent the pull in last week to the team... hmmmm

On Thu, May 5, 2016 at 8:32 PM, Greg Martin notifications@github.com
wrote:

> That's great, do you know when that will happen?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/jamesmontemagno/steps-set-android-manifest-versions/issues/6#issuecomment-217235696

## 

James Montemagno
http://www.montemagno.com
@jamesmontemagno http://www.twitter.com/jamesmontemagno

**Comment by gregorymartin** [comment]
@jamesmontemagno, according to the Bitrise team you "created the new version, but didn't share it into the Step Lib".

**Comment by jamesmontemagno** [comment]
Should be live: https://github.com/jamesmontemagno/bitrise-steplib just need to have them pull it in

**Comment by gregorymartin** [comment]
They are saying they need a pull request to be initiated for it.

**Comment by jamesmontemagno** [comment]
Ahhhh yeah that is what I forgot to do :) tehehe

**Comment by jamesmontemagno** [comment]
Done!
