### ISSUE TITLE
Support build.gradle as input for versioning

### ISSUE THREAD

**Issue by apacha** [jamesmontemagno/steps-set-android-manifest-versions#8]
Newer Android-projects don't specify the version number any more in the AndroidManifest.xml but in the applications build.gradle file.

It would be great, if there was a similar step, that sets the version number in the build.gradle.

**Comment by thebergamo** [comment]
This module is pretty nice, but needs to update `build.gradle` too, not only the `AndroidManifest.xml`

**Comment by jamesmontemagno** [comment]
I do not have any plans to add support as this is a cross platform solution that can do any platform regardless of gradle such as Xamarin/Cordova/ReactNative apps. I think that should be a separate step.

**Comment by apacha** [comment]
True, there should be a separate step, that performs the versioning in build.gradle. If anyone creates that step or finds one, please link it to this issue. Thanks
