### ISSUE TITLE
Version Code offset being set against code in AndroidManifest.xml not in Bitrise build

### ISSUE THREAD

**Issue by gregorymartin** [jamesmontemagno/steps-set-android-manifest-versions#9]
I would expect the version code to be the bitrise build # + the offset, and ignore whatever is in the versionCode in the android manifest file, however, the plugin appears to detect the value in the manifest and use that instead of the bitrise build number.

**Comment by gregorymartin** [comment]
I just submitted a PR to address this.

**Comment by jamesmontemagno** [comment]
Pushing now!
